# Generated by Django 5.1.1 on 2024-09-18 02:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Artigo')),
                ('descricao_artigo', models.TextField(verbose_name='Descrição do Artigo')),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Publicação')),
                ('resumo_artigo', models.CharField(max_length=500, verbose_name='Resumo do Artigo')),
                ('meta_keywords', models.CharField(max_length=255, verbose_name='Palavras-chave (SEO)')),
                ('meta_description', models.CharField(max_length=255, verbose_name='Descrição Meta (SEO)')),
            ],
            options={
                'verbose_name': 'Artigo',
                'verbose_name_plural': 'Artigos',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(verbose_name='Comentário')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='home.artigo', verbose_name='Artigo')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['-data'],
            },
        ),
    ]
