# Generated by Django 5.1.1 on 2024-09-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='canonical_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Canônica'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='imagem_capa',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/', verbose_name='Imagem de Capa'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=200, unique=True, verbose_name='Slug'),
        ),
    ]
